repo: https://github.com/Bayu12345677/library_instagram
filename: FUNDING.yml
github: ["https://github.com/Bayu12345677/", Bayu12345677]
custom: ["https://www.paypal.me/polygons1","https://saweria.co/Polygon"]
